export function serialize(ontology, opts = {}) {
  const header = opts.header
    ? `// Generated by @intent-driven/importer-postgres at ${new Date().toISOString()}\n// Не редактируй секции, помеченные @generated. Остальное — твоё.\n\n`
    : "";
  const body = `export const ontology = ${stringify(ontology, 2)};\n`;
  return header + body;
}

function stringify(value, indent = 2, level = 0) {
  const pad = " ".repeat(indent * level);
  const nextPad = " ".repeat(indent * (level + 1));

  if (value === null) return "null";
  if (value === undefined) return "undefined";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]";
    const items = value.map((v) => nextPad + stringify(v, indent, level + 1));
    return "[\n" + items.join(",\n") + "\n" + pad + "]";
  }

  if (typeof value === "object") {
    const keys = Object.keys(value);
    if (keys.length === 0) return "{}";
    const entries = keys.map((k) => {
      const keyStr = /^[a-zA-Z_$][\w$]*$/.test(k) ? k : JSON.stringify(k);
      return nextPad + keyStr + ": " + stringify(value[k], indent, level + 1);
    });
    return "{\n" + entries.join(",\n") + "\n" + pad + "}";
  }

  return JSON.stringify(value);
}
