import { describe, it, expect } from "vitest";
import { serialize } from "../src/serialize.js";

describe("serialize", () => {
  it("генерит export const ontology с правильной структурой", () => {
    const ontology = {
      name: "default",
      entities: {
        Task: { name: "Task", kind: "internal", fields: { id: { type: "string" } } },
      },
      intents: {
        createTask: { target: "Task", alpha: "insert", parameters: {} },
      },
      roles: {},
    };
    const output = serialize(ontology);

    expect(output).toContain("export const ontology =");
    expect(output).toContain("Task:");
    expect(output).toContain("createTask:");
  });

  it("валидный JS, исполнимый через dynamic import", async () => {
    const ontology = {
      name: "default",
      entities: { Task: { name: "Task", kind: "internal", fields: {} } },
      intents: {},
      roles: {},
    };
    const src = serialize(ontology);

    const dataUrl =
      "data:text/javascript;base64," + Buffer.from(src).toString("base64");
    const mod = await import(dataUrl);
    expect(mod.ontology.name).toBe("default");
    expect(mod.ontology.entities.Task.name).toBe("Task");
  });

  it("добавляет header-комментарий с timestamp при opts.header", () => {
    const ontology = { name: "default", entities: {}, intents: {}, roles: {} };
    const src = serialize(ontology, { header: true });
    expect(src).toMatch(/^\/\/ Generated by @intent-driven\/importer-postgres/);
  });
});
